services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/src/notes_app/infrastructure/database/notes_app_database.db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./src/notes_app/infrastructure/database:/app/src/notes_app/infrastructure/database
      - ./alembic:/app/alembic
    depends_on:
      kafka:
        condition: service_healthy

  kafka:
    image: bitnami/kafka:3.7
    hostname: kafka
    environment:
      KAFKA_CFG_NODE_ID: "0"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LISTENERS: "CONTROLLER://:19092,PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "0@kafka:19092"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      start_period: 20s
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  kafka-data:
