name: CI

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          enable-cache: true
      - name: Install project dependencies
        run: uv sync --all-groups --all-extras
      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: |
            ./.venv
            ~/.local/share/uv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
  ruff:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore cached venv
        uses: actions/cache@v4
        with:
          path: |
            ./.venv
            ~/.local/share/uv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
      - name: Lint with ruff check
        run: ./.venv/bin/ruff check
      - name: Lint with ruff format
        run: ./.venv/bin/ruff format --check
  mypy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore cached venv
        uses: actions/cache@v4
        with:
          path: |
            ./.venv
            ~/.local/share/uv
          key: venv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
      - name: Lint with mypy check
        run: ./.venv/bin/mypy src